export const routes = [
  {
    title: "Home",
    href: "/",
  },
  {
    title: "Portfolio",
    href: "/portfolio",
  },
  {
    title: "How It Works",
    href: "/how-it-works",
  },
  {
    title: "About",
    href: "/about",
  },
  {
    title: "Jobs",
    href: "/jobs",
  },
  {
    title: "Contact",
    href: "/contact",
  },
];

export const industries = [
  { value: "internetServices", title: "Internet Services" },
  { value: "music", title: "Music" },
  { value: "sustainability", title: "Sustainability" },
  { value: "events", title: "Events" },
  { value: "legal", title: "Legal" },
  { value: "professionalServices", title: "Professional Services" },
  { value: "lendingAndInvestments", title: "Lending and Investments" },
  { value: "sports", title: "Sports" },
  { value: "blockchainAndCrypto", title: "Blockchain and Crypto" },
  { value: "hrAndRecruiting", title: "HR and Recruiting" },
  { value: "telecommunication", title: "Telecommunication" },
  { value: "realEstate", title: "Real Estate" },
  { value: "administrativeServices", title: "Administrative Services" },
  { value: "software", title: "Software" },
  { value: "informationTechnology", title: "Information Technology" },
  { value: "deepTech", title: "DeepTech" },
  { value: "health", title: "Health" },
  { value: "dataAndAnalytics", title: "Data and Analytics" },
  { value: "communityAndLifestyle", title: "Community and Lifestyle" },
  { value: "media", title: "Media" },
  { value: "agricultureAndFarming", title: "Agriculture and Farming" },
  { value: "hardware", title: "Hardware" },
  { value: "commerceAndShopping", title: "Commerce and Shopping" },
  { value: "consumerProducts", title: "Consumer Products" },
  { value: "manufacturing", title: "Manufacturing" },
  { value: "salesAndMarketing", title: "Sales and Marketing" },
  { value: "design", title: "Design" },
  { value: "advertising", title: "Advertising" },
  { value: "mobilePlatformsApps", title: "Mobile, Platforms, and Apps" },
  { value: "construction", title: "Construction" },
  { value: "clothingAndApparel", title: "Clothing and Apparel" },
  { value: "travelAndTourism", title: "Travel and Tourism" },
  { value: "security", title: "Security" },
  { value: "finance", title: "Finance" },
  { value: "food", title: "Food" },
  { value: "gaming", title: "Gaming" },
  { value: "biotechnology", title: "Biotechnology" },
  { value: "contentAndPublishing", title: "Content and Publishing" },
  { value: "education", title: "Education" },
];

export const jobTypes = [
  "Full-time",
  "Part-time",
  "Freelance",
  "Internship",
  "Contract",
];
